### ISSUE TITLE
Labels of the slices are mismatching

### ISSUE THREAD

**Issue by karthikloganlogan** [obss/sahi#536] opened 2022-07-26 12:01 UTC
I had a dataset in coco json format. After slicing with sahi , i found out that many labels are wrongly mapped (mismatched).

**Comment by fcakyon** [comment] 2022-07-26 12:09
Can you provide sample image files and annotation json, your sahi version, the script or command you are using?

**Comment by karthikloganlogan** [comment] 2022-07-27 12:02
I cant share you the images since they are confidential. But i can share yout the annotation file. 
sahi version : 0.10.1
command used : sahi coco slice --image_dir /content/solar/images/train --dataset_json_path /content/output/labels.json --slice_size 1264 --overlap_ratio 0.2 --output_dir /content/sliced_solar
/ --ignore_negative_samples True 
[annotation_Folder.zip](https://github.com/obss/sahi/files/9198448/annotation_Folder.zip)

**Comment by devrimcavusoglu** [comment] 2022-07-27 13:27
@karthikloganlogan I don't think this would help without images. Can you provide minimal reproducable example with some mock image and annotation file for us to replicate ?

**Comment by fcakyon** [comment] 2022-08-01 08:24
Closing this issue since we are not able to recreate it.

**Closed by fcakyon** 2022-08-01 08:24 UTC
