### ISSUE TITLE
yolov4 support

### ISSUE THREAD

**Issue by Fetulhak** [obss/sahi#139] opened 2021-06-17 09:59 UTC
@fcakyon I have trained and YOLOV4 model using AlexyAB's repo and I have generated a weight file for my custom dataset which was sliced using your repo. Now I want to check the test results for predicted YOLOV4 results. How can I integrate YOLOV4 weight file to your test folder so that I can use the YOLOV4 like you have used the YOLOV5 model which was from from ultralytics repo.

**Comment by fcakyon** [comment] 2021-06-17 10:02
@Fetulhak thanks alot for your interest! You can check readme for extending detection framework support of the `sahi`: https://github.com/obss/sahi#contributing

`sahi` library currently supports all [YOLOv5 models](https://github.com/ultralytics/yolov5/releases) and [MMDetection models](https://github.com/open-mmlab/mmdetection/blob/master/docs/model_zoo.md). Moreover, it is easy to add new frameworks.

All you need to do is, creating a new class in [model.py](sahi/model.py) that implements [DetectionModel class](https://github.com/obss/sahi/blob/651f8e6cdb20467815748764bb198dd50241ab2b/sahi/model.py#L10). You can take the [MMDetection wrapper](https://github.com/obss/sahi/blob/651f8e6cdb20467815748764bb198dd50241ab2b/sahi/model.py#L164) or [YOLOv5 wrapper](https://github.com/obss/sahi/blob/ffa168fc38b75a002a0117f1fdde9470e1a9ce8c/sahi/model.py#L363) as a reference.

**Comment by fcakyon** [comment] 2021-06-17 10:11
@Fetulhak can you provide a minimal example for performing inference on YOLOv4? I can work on a YOLOv4 wrapper if you provide minimal example.

**Comment by Fetulhak** [comment] 2021-06-17 11:46
I am reading on TensorFlow version of YOLOv4 which you can find it here and it can be installed using pip 
  https://wiki.loliot.net/docs/lang/python/libraries/yolov4/python-yolov4-about/

here is the code used for inference in YOLOv4. 

import cv2

from yolov4.tf import YOLOv4

yolo = YOLOv4()

yolo.config.parse_names("coco.names")
yolo.config.parse_cfg("yolov4-tiny.cfg")

yolo.make_model()
yolo.load_weights("yolov4-tiny.weights", weights_type="yolo")
yolo.summary(summary_type="yolo")
yolo.summary()

yolo.inference(media_path="kite.jpg")

yolo.inference(media_path="road.mp4", is_image=False)

yolo.inference(
    "/dev/video0",
    is_image=False,
    cv_apiPreference=cv2.CAP_V4L2,
    cv_frame_size=(640, 480),
    cv_fourcc="YUYV",
)

**Comment by fcakyon** [comment] 2021-06-17 12:04
@Fetulhak thanks for providing minimal sample!

Have tried training yolov5 via this repo? https://github.com/fcakyon/yolov5-pip 

It is really straightforward, stable, fast and accurate :)

**Comment by Fetulhak** [comment] 2021-06-17 12:15
@Fetulhak No, I did not use YOLOv5. I have been working on YOLOV3 and V4 still now. But I will use it to compare my results.

**Comment by Fetulhak** [comment] 2021-06-24 14:39
@fcakyon I create a new class for yolov4 inference. Here i have attached the modified model.py and I have also create a new yolov4.py under sahi/utils similar to yolov5. however I am getting an error during model initialization in my new class for yolov4. I have also attached .ipynb modified from the yolov5 inference ipynb. I need you help. just replace your model.py with the one I attached here. insert yolov4.py under utils and run .ipynb attached here

[model.txt](https://github.com/obss/sahi/files/6710057/model.txt)
[yolov4.txt](https://github.com/obss/sahi/files/6710058/yolov4.txt)

**Comment by fcakyon** [comment] 2021-06-24 22:29
@Fetulhak thanks a lot for providing your scripts! Which package should I use to reproduce your results? `pip install yolov4` ?

**Comment by Fetulhak** [comment] 2021-06-24 22:52
@

> @Fetulhak thanks a lot for providing your scripts! Which package should I use to reproduce your results? `pip install yolov4` ?

Yes you can use pip install yolov4. I am using this project https://wiki.loliot.net/docs/lang/python/libraries/yolov4/python-yolov4-about


here is the procedures I follow for yolov4 inference. here is the text file form of the .ipynb file i have been using
[inference_for_yolov5.txt](https://github.com/obss/sahi/files/6712489/inference_for_yolov5.txt)

**Comment by fcakyon** [comment] 2021-06-26 00:13
@Fetulhak your `yolov4.py` file is incorrect, here is the fixed version:

```python
from typing import Optional
from sahi.utils.file import download_from_url


class Yolov4TestConstants:
    YOLOV4_MODEL_URL = "https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-tiny.weights"
    YOLOV4_MODEL_PATH = "tests/data/models/yolov4/yolov4-tiny.weights"
    YOLOV4_CONFIG_URL = "https://raw.githubusercontent.com/hhk7734/tensorflow-yolov4/master/config/yolov4-tiny.cfg"
    YOLOV4_CONFIG_PATH = "tests/data/models/yolov4/yolov4-tiny.cfg"
    YOLOV4_NAMES_URL = "https://raw.githubusercontent.com/hhk7734/tensorflow-yolov4/master/test/dataset/coco.names"
    YOLOV4_NAMES_PATH = "tests/data/models/yolov4/coco.names"


def download_yolov4_model(destination_path: Optional[str] = None):

    if destination_path is None:
        destination_path = Yolov4TestConstants.YOLOV4_MODEL_PATH

    download_from_url(Yolov4TestConstants.YOLOV4_MODEL_URL, destination_path)
    download_from_url(Yolov4TestConstants.YOLOV4_CONFIG_URL, Yolov4TestConstants.YOLOV4_CONFIG_PATH)
    download_from_url(Yolov4TestConstants.YOLOV4_NAMES_URL, Yolov4TestConstants.YOLOV4_NAMES_PATH)
```

and here is the updated version of `Yolov4DetectionModel`:

```python
class Yolov4DetectionModel(DetectionModel):
    def load_model(self):
        """
        Detection model is initialized and set to self.model.
        """
        try:
            from yolov4.tf import YOLOv4
        except ImportError:
            raise ImportError('Please run "pip install -U yolov4" ' "to install YOLOv4 first for YOLOv4 inference.")

        # set model

        try:
            model = YOLOv4()
            print(" i was here")
            model.config.parse_names(self.names_path)
            print(" i was here 2")
            model.config.parse_cfg(cfg_path=self.config_path)
            print(" i was  here 3")
            model.make_model()
            print(" i was here 4")
            model.load_weights(self.model_path, weights_type="yolo")
            print(" i was  here 5")
            self.model = model
        except Exception as e:
            TypeError("model_path is not a valid yolov4 model path: ", e)

        # set category_mapping

        if not self.category_mapping:
            category_mapping = {str(ind): category_name for ind, category_name in enumerate(self.category_names)}
            self.category_mapping = category_mapping

    def perform_inference(self, image: np.ndarray):
        """
        Prediction is performed using self.model and the prediction result is set to self._original_predictions.
        Args:
            image: np.ndarray
                A numpy array that contains the image to be predicted.
        """
        try:
            from yolov4.tf import YOLOv4
        except ImportError:
            raise ImportError('Please run "pip install -U yolov4" ' "to install YOLOv4 first for YOLOv4 inference.")

        # Confirm model is loaded
        assert self.model is not None, "Model is not loaded, load it by calling .load_model()"

        # prediction_result = self.model(image)
        prediction_result = self.model.inference(media_path="kite.jpg")

        self._original_predictions = prediction_result
        print(prediction_result)

    @property
    def num_categories(self):
        """
        Returns number of categories
        """
        return len(self.model.config.names)

    @property
    def has_mask(self):
        """
        Returns if model output contains segmentation mask
        """
        has_mask = self.model.with_mask
        return has_mask

    @property
    def category_names(self):
        return list(self.model.config.names.values())
```

**Comment by fcakyon** [comment] 2021-06-26 00:13
@Fetulhak would you try the updated versions and report back?

**Comment by Fetulhak** [comment] 2021-06-26 16:32
> @Fetulhak would you try the updated versions and report back?

@fcakyon Thanks for your update. I will try and update you on my findings.

**Comment by Fetulhak** [comment] 2021-06-27 09:56
@fcakyon now the yolov4 class preform-inference works with a little modification as shown below

`    def perform_inference(self, image: np.ndarray):
        """
        Prediction is performed using self.model and the prediction result is set to self._original_predictions.
        Args:
            image: np.ndarray
                A numpy array that contains the image to be predicted.
        """
        try:
            from yolov4.tf import YOLOv4
        except ImportError:
            raise ImportError('Please run "pip install -U yolov4" ' "to install YOLOv4 first for YOLOv4 inference.")

        # Confirm model is loaded
        assert self.model is not None, "Model is not loaded, load it by calling .load_model()"

        # prediction_result = self.model(image)
        #prediction_result = self.model.inference(media_path="kite.jpg")
         prediction_result = self.model.predict(image,self.prediction_score_threshold)

        self._original_predictions = prediction_result
        print(prediction_result)

    @property
    def num_categories(self):
        """
        Returns number of categories
        """
        return len(self.model.config.names)

    @property
    def has_mask(self):
        """
        Returns if model output contains segmentation mask
        """
        has_mask = self.model.with_mask
        return has_mask

    @property
    def category_names(self):
        return list(self.model.config.names.values())`

The problem is now prediction results that you use for yolov5 is in xyxy format and the predicition result we get from yolov4 is in xywh normalized format. we need a code to change the yolov4 format to yolov5 format.


prediction results for yolov4 are dispalyed as shown below

          x                    y                  w              h               class id         prob
 [[ 0.46750453  0.1268725   0.05431676  0.08310144     33.          0.96195537]
 [ 0.10399829  0.7547927   0.03737793  0.15918408       0.          0.90549564]
 [ 0.1795966   0.86352164  0.0404276   0.17934994        0.          0.6798486 ]]



prediction resutls for yolov5 are dispalyed as shwon below

        tensor(
             x left                     y top          x bottom          y right          prob              cls id   
        [[3.22013e+02, 3.22174e+02, 3.83605e+02, 3.62460e+02, 8.41712e-01, 2.00000e+00],
        [4.48575e+02, 3.08800e+02, 4.96908e+02, 3.42803e+02, 8.12179e-01, 2.00000e+00],
        [7.64908e+02, 2.60927e+02, 7.94061e+02, 2.83598e+02, 7.08609e-01, 2.00000e+00],
        [6.04125e+02, 2.37290e+02, 6.28566e+02, 2.59425e+02, 6.82913e-01, 2.00000e+00],
        [8.33987e+02, 3.09424e+02, 8.73408e+02, 3.43815e+02, 6.76855e-01, 2.00000e+00],
        [6.17475e+02, 1.95396e+02, 6.41394e+02, 2.18711e+02, 6.58656e-01, 2.00000e+00],
        [3.82050e+02, 2.80206e+02, 4.18973e+02, 3.04781e+02, 5.94899e-01, 2.00000e+00],
        [7.20075e+02, 2.43860e+02, 7.47353e+02, 2.71261e+02, 5.94134e-01, 2.00000e+00],
        [7.00413e+02, 2.34649e+02, 7.21405e+02, 2.50182e+02, 5.67551e-01, 2.00000e+00],
        [7.58754e+02, 2.31797e+02, 7.82001e+02, 2.47634e+02, 4.85633e-01, 2.00000e+00],
        [5.63651e+02, 2.40792e+02, 5.87714e+02, 2.61235e+02, 4.09187e-01, 2.00000e+00],
        [6.49051e+02, 1.98626e+02, 6.70245e+02, 2.14714e+02, 3.38123e-01, 2.00000e+00],
        [7.87568e+02, 1.74923e+02, 1.05628e+03, 5.75780e+02, 2.69586e-01, 6.00000e+00],
        [5.44113e+02, 2.33241e+02, 5.65153e+02, 2.53217e+02, 2.62741e-01, 2.00000e+00]])

 here is the text file for my draft _create_object_prediction_list_from_original_predictions function for Yolov4DetectionModel class

[model.txt](https://github.com/obss/sahi/files/6721358/model.txt)

**Comment by fcakyon** [comment] 2021-06-27 13:28
@Fetulhak If you multiply the bbox coords with image height and width, you get the sahi format. You have to implement `_create_object_prediction_list_from_original_predictions` such that it iterates over yolov4 predictions and sets `self.object_prediction_list` with a list of `sahi.prediction.ObjectPrediction` like this:

```python
from typing imporT List
from sahi.prediction import ObjectPrediction

def _create_object_prediction_list_from_original_predictions(
    self,
    shift_amount: Optional[List[int]] = [0, 0],
    full_shape: Optional[List[int]] = None,
):
    # you have to set self._original_predictions as yolov4 prediction result in 'perform_inference' function
    yolov4_predictions = self._original_predictions
    # include image size in yolov4_predictions in 'perform_inference' function and parse them here:
    image_height = yolov4_predictions.image_height
    image_width = yolov4_predictions.image_width
    # init empty object_prediction_list
    object_prediction_list: List[ObjectPrediction] = []
    # iterate over yolov4_predictions and convert them to ObjectPrediction object
    for prediction in yolov4_predictions:
        # bbox = [xmin, ymin, xmax, ymax]
        bbox = [
            prediction.x*image_width,
            prediction.y*image_height,
            (prediction.x + prediction.width)*image_width,
            (prediction.y + prediction.height)*image_height
        ]  
        object_prediction = ObjectPrediction(
            bbox=bbox,
            category_id=prediction.class_id,
            score=prediction.prob,
            shift_amount=shift_amount,
            full_shape=full_shape,
        )
        object_prediction_list.append(object_prediction)
    # set self._object_prediction_list
    self._object_prediction_list = object_prediction_list
```

**Comment by Fetulhak** [comment] 2021-06-28 14:52
Hi @fcakyon Thanks now I have converted the prediction results of yolov4 as you suggested. Now there is one error which is the yolov4 prediction does not have .names field and I can't proceed 

 ```
 def _create_object_prediction_list_from_original_predictions(
        self,
        shift_amount: Optional[List[int]] = [0, 0],
        full_shape: Optional[List[int]] = None,):
        """
        self._original_predictions is converted to a list of prediction.ObjectPrediction and set to
        self._object_prediction_list.

        Args:
            shift_amount: list
                To shift the box and mask predictions from sliced image to full sized image, should be in the form of [shift_x, shift_y]
            full_shape: list
                Size of the full image after shifting, should be in the form of [height, width]
        """
        original_predictions = self._original_predictions

        image_height = original_predictions[len(original_predictions)-1][0]
        image_width = original_predictions[len(original_predictions)-1][1]
        
        object_prediction_list = []

        # process predictions
        for prediction in original_predictions[:-1]:
            
            bbox = [
            (prediction[0]- prediction[1])*image_width,
            (prediction[1]-prediction[3])*image_height,
            (prediction[0] + prediction[1])*image_width,
            (prediction[1] + prediction[3])*image_height] 

            score = prediction[5].item()
            category_id = int(prediction[4].item())
            print("I was here ")
            category_name = original_predictions.names[category_id] #this is where the error is occured
            print("iwas here too")

            object_prediction = ObjectPrediction(
                bbox=bbox,
                category_id=category_id,
                score=score,
                bool_mask=None,
                category_name=category_name,
                shift_amount=shift_amount,
                full_shape=full_shape,
            )
            object_prediction_list.append(object_prediction)

        self._object_prediction_list = object_prediction_list
        print(object_prediction_list)
```

**Comment by fcakyon** [comment] 2021-06-28 21:45
@Fetulhak you can use 
```python
self.category_names[category_id]
``` 
to get the category names after defining 

```python
    @property
    def num_categories(self):
        """
        Returns number of categories
        """
        return len(self.model.config.names)
```
in Yolov4DetectionModel class.

**Comment by fcakyon** [comment] 2021-06-28 21:47
@Fetulhak Refer to this yolov4detectionmodel code for more detail: https://github.com/obss/sahi/blob/0ebe1a7a3c0e3d8198b55d789287944ce7a5792b/sahi/model.py#L553

**Comment by Fetulhak** [comment] 2021-06-30 20:29
@fcakyon Thank you very much. I can generate both the sliced prediction and the original prediction now_
![sliced_prediction](https://user-images.githubusercontent.com/46393025/124026787-c8de5f00-d9fa-11eb-89f8-8c07cdda49a0.png)
![full_size_prediction](https://user-images.githubusercontent.com/46393025/124026877-e8758780-d9fa-11eb-88da-9a8154f85d5f.png)
_

**Comment by Fetulhak** [comment] 2021-06-30 20:35
The above results are obtained using slice size of 512 but when I reduce slice size 256 an error occurred due to negative bounding box coordinates.

```
result = get_sliced_prediction(
    image,
    detection_model,
    slice_height = 256,
    slice_width = 256,
    overlap_height_ratio = 0.2,
    overlap_width_ratio = 0.2
)
```
.
.
.
.

/usr/local/lib/python3.7/dist-packages/sahi/annotation.py in __init__(self, box, shift_amount)
     31         """
     32         if box[0] < 0 or box[1] < 0 or box[2] < 0 or box[3] < 0:
---> 33             raise Exception("Box coords [minx, miny, maxx, maxy] cannot be negative")
     34         self.minx = int(box[0])
     35         self.miny = int(box[1])

Exception: Box coords [minx, miny, maxx, maxy] cannot be negative

**Comment by Fetulhak** [comment] 2021-06-30 20:48
@fcakyon How the predictions in the sliced images will become negative coordinate? is it during the merge operation?

**Comment by fcakyon** [comment] 2021-06-30 21:05
@Fetulhak could you please send me your full code so i can reproduce the results?

**Comment by Fetulhak** [comment] 2021-06-30 21:18
This is the colab notebook I am working with.  
[Copy_of_inference_for_yolov5.zip](https://github.com/obss/sahi/files/6744045/Copy_of_inference_for_yolov5.zip)
and this is the original kite.jpg image

**Comment by fcakyon** [comment] 2021-07-05 19:51
@Fetulhak negative box coordinates issue is fixed in v0.5.2: https://github.com/obss/sahi/releases/tag/0.5.2 

Install latest version with `pip install -U sahi`

**Comment by Fetulhak** [comment] 2021-07-06 16:04
@fcakyon original image size was 750x750 and I sliced it to 320x320, 416x416,608x608. for all the slices it gives me 0 detection results even though I have 3 detections in the original size as shown in the provided figure. I was just practicing and I thought I will get more detection results from the sliced ones. I am curious why this happened. any parameters to adjust. 
full-size  detection 
![prediction (3)](https://user-images.githubusercontent.com/46393025/124630863-7c2bd580-de8b-11eb-8051-ad623a112a57.png)

**Comment by fcakyon** [comment] 2021-07-06 17:28
@Fetulhak it is not normal. Which prediction script/function are you using?

**Comment by Fetulhak** [comment] 2021-07-07 05:55
@fcakyon I am using yolov4 model to predict results.

**Comment by fcakyon** [comment] 2021-07-07 08:53
@Fetulhak I know that. I am asking which function you are using. `get_prediction`, `get_sliced_prediction` or `predict`?

You have to set `no_standard_prediction=False` and `no_sliced_prediction=False` in `predict` function for the best performance.

If you are using `get_sliced_prediction` function, then you have to set `perform_standard_pred=True`.

**Comment by Fetulhak** [comment] 2021-07-07 08:57
@fcakyon I am using get_prediction for full image size prediction and get_sliced_prediction to generate prediction results for the sliced cases. I will check those values and let you know my results if improved.

**Comment by Fetulhak** [comment] 2021-07-07 09:00
@fcakyon BTW the Exception: Box coords [minx, miny, maxx, maxy] cannot be negative still exist after following your suggestion to install the new version using the command `pip install -U sahi`

**Comment by fcakyon** [comment] 2021-07-07 09:02
@Fetulhak can you give me your code, sample image and parameters you used so that i can recreate the issue? Because in my end that error is fixed.

**Comment by Fetulhak** [comment] 2021-07-07 09:05
@fcakyon can I communicate with you through mail to give you the link to my G-drive. here is my e-mail : afetulhak@yahoo.com

**Comment by fcakyon** [comment] 2021-12-24 14:16
closing this since its not a priority at the moment

**Closed by fcakyon** 2021-12-24 14:16 UTC
Labels: enhancement, good first issue, help wanted
