### ISSUE TITLE
Misguidedly assigned image_id in results.json output from sahi predict

### ISSUE THREAD

**Issue by tureckova** [obss/sahi#298] opened 2021-12-07 10:22 UTC
Hello,
I generated the result.json via Sahi predict script and tried to run evaluation:
```
sahi coco evaluate \
    --dataset_json_path coco_360ann-v1.4/JPEGImages-test/test.json \
    --result_json_path runs/predict/exp/result.json \
    --out_dir coco_analysis
```
, but got this error:

> loading annotations into memory...
> Done (t=0.01s)
> creating index...
> index created!
> 
> Evaluating bbox...
> Loading and preparing results...
> Traceback (most recent call last):
>   File "/usr/local/bin/sahi", line 8, in <module>
>     sys.exit(app())
>   File "/usr/local/lib/python3.8/dist-packages/sahi/cli.py", line 24, in app
>     fire.Fire(sahi_app)
>   File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
>     component_trace = _Fire(component, args, parsed_flag_args, context, name)
>   File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 466, in _Fire
>     component, remaining_args = _CallAndUpdateTrace(
>   File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
>     component = fn(*varargs, **kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/sahi/scripts/coco_evaluation.py", line 361, in main
>     eval_results = evaluate_coco(
>   File "/usr/local/lib/python3.8/dist-packages/sahi/scripts/coco_evaluation.py", line 137, in evaluate_coco
>     cocoDt = cocoGt.loadRes(results)
>   File "/usr/local/lib/python3.8/dist-packages/pycocotools/coco.py", line 326, in loadRes
>     assert set(annsImgIds) == (set(annsImgIds) & set(self.getImgIds())), \
> AssertionError: Results do not correspond to current coco set

The predict script runs without error; even the visuals_with_gt folder is generated. The data looked good to me, so I explored the JSON files. It seems that in results.json you do not assign the image_id right.

I have also attached the JSON files in question.
[annotations.zip](https://github.com/obss/sahi/files/7667224/annotations.zip)

Can you please have a look?
Thank you very much for your help.

**Comment by fcakyon** [comment] 2021-12-07 18:06
Thanks a lot for the feedback @tureckova!

We are using `sahi predict`, `sahi coco evaluate` and `sahi coco analysis` commands on daily basis without any issues. Could you give more detail so that I can spot the issue?

What is your `sahi` version? You can update to the latest version by: `pip install -U sahi`

Which arguments and parameters have you used for `sahi predict` command?

**Comment by tureckova** [comment] 2021-12-07 22:17
Thank you for your reaction.
I have the 0.8.13 version.

I use this set up of predict script:
```
sahi predict \
    --slice_width 2448 \
    --slice_height 1469 \
    --overlap_height_ratio 0.2 \
    --overlap_width_ratio 0.2 \
    --model_confidence_threshold 0.25\
    --source /mnt/SSD1TBdrive/TACR_TREND/data/2021-09-07_tomato-row/coco_360ann-v1.4/JPEGImages-test/ \
    --model_path epoch_15.pth \
    --model_config_path faster_rcnn_r50_fpn_attention_0010-tomato_row.py \
    --model_type mmdet \
    --postprocess_type NMS \
    --postprocess_match_threshold 0.5 \
    --postprocess_match_metric IOS \
    --no_standard_prediction \
    --export_visual \
    --dataset_json_path /mnt/SSD1TBdrive/TACR_TREND/data/2021-09-07_tomato-row/coco_360ann-v1.4/JPEGImages-test/test.json \
```

**Comment by fcakyon** [comment] 2021-12-07 22:31
@tureckova I have confirmed the typo regarding `image_id`. Can you please `pip uninstall sahi` then `pip install git+https://github.com/obss/sahi.git@fix-predict` and try again if ids are created correctly?

**Comment by tureckova** [comment] 2021-12-08 14:59
@fcakyon I did install a fixed version, and the image ids are OK, at least as I can tell from viewing and the coco evaluate script works. But the predictions are weird - there are only one or two detections in each image now, although I am using the same model as before.
The output JSON file is here:
[result.zip](https://github.com/obss/sahi/files/7676872/result.zip)

**Comment by fcakyon** [comment] 2021-12-08 15:14
@tureckova have you tried different `postprocess_type` , `slice_size`, `model_confidence_threshold`? What was your prior `sahi` version?

**Comment by tureckova** [comment] 2021-12-08 18:24
@fatih Well,I the left the set up the same as before and there had been
much more predictions as you can see in the previous JSON file with results.

**Comment by fcakyon** [comment] 2021-12-08 19:09
@tureckova I changed only 1 line (related to image id) in the `fix-predict` branch so the difference in the prediction result is not related with my fix. 

Can you tell me what you have changed between the previous run and this run? What was the `sahi` version previously?

**Comment by tureckova** [comment] 2021-12-08 21:23
@fcakyon I tested the setup with different versions.
I originally used the version sahi==0.8.9 where you fixed the RGB channel order for mmdetection models #265, the predictions are fine except for the image ids. 
Starting from the version sahi==0.8.12 the predictions are faulty and so are the image ids.

**Comment by fcakyon** [comment] 2021-12-09 08:00
@tureckova before 0.8.12, there was a bug on NMS postprocess, it is fixed with 0.8.12: https://github.com/obss/sahi/releases/tag/0.8.12

So here is what you can do to have more predictions:
- use lower `postprocess_match_threshold`
- change `postprocess_type`
- change `postprocess_match_metric`
- use lower `model_confidence_threshold `

So `sahi` is working as intended, you have to play with the params to have better results.

**Comment by fcakyon** [comment] 2021-12-09 08:06
Additionaly `image_id` bug was present on v0.8.9-v0.8.13, it is only fixed in v0.8.14.

**Closed** 2021-12-09 18:31 UTC
Labels: bug, help wanted

**Comment by tureckova** [comment] 2021-12-09 20:11
@fcakyon, thank you for your advice. When I changed the setup as suggested, the results were better.
But now I can see a problem with category id. I overlooked this before, sorry. The category_name is correct, but the category_id is different than it should be according to the original JSON file. Could you have a look at it, please?

**Comment by fcakyon** [comment] 2021-12-09 20:15
@tureckova it it most probably related with your training setup, can you provide your mmdet training config (and trained model). Because category names and ids are directly acquired from your provided mmdetection model file.

So please update your coco category names and ids to be same with your mmdetection model (category ids should start from 0, and there should be no background category).

**Comment by tureckova** [comment] 2021-12-11 10:05
@fcakyon, thank you for your valuable advice. The truth is that in mmdet config, I have only the valid categories, while there is also the category "_backgroud_" in the original dataset JSON. To be honest, I am sometimes a bit lost whether the background category is on is not necessary. The modification of dataset JSON solved my problem. Thank you very much for your help.

**Comment by fcakyon** [comment] 2021-12-11 11:14
@tureckova glad to see your issue solved! Yes background class may be confusing in classification/object detection implementation :)

**Comment by tureckova** [comment] 2022-01-20 16:59
@fcakyon I tried the fifty-one visualization script and it seems that it has similar troubles with image ids as had the coco evaluate script discussed above. It obviously matches the predictions for a different image than the ground truth values came from.
Can you possibly check it? Thank you very much for your help :pray:

**Comment by fcakyon** [comment] 2022-01-20 22:23
@tureckova what is your sahi version?

**Comment by tureckova** [comment] 2022-01-21 11:24
You are right, I had v0.8.19 :astonished: , the upgrade fixed it. Thank you.
